# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-17 16:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_template', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='category',
            new_name='name',
        ),
    ]
