# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-25 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_template', '0002_auto_20170417_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteruser',
            name='user_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
